%% Input data and assumptions provided
% See document SAG control simulator.pdf

% Normal operating points
op_pts = struct( ...
    'ore_feed', 120, ...   % changed from 108 to increase effects
    'SAG_speed', 0.77, ...
    'mill_level', 19.2, ...
    'mill_power', 1812, ...
    'ore_hardness', 1, ...
    'ore_density', 2.9, ...
    'mix_factor', 0.2283, ...
    'feed_water_ratio',  0.3410 ...
);
